/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useEffect, useMemo, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame, type ThreeElements } from '@react-three/fiber'
import type { Group, Mesh, MeshStandardMaterial } from 'three'
import type { GLTF } from 'three-stdlib'

const DRONE_NODE_KEY = 'tripo_node_abc4b498-0870-4cc4-87fa-155237fcc087'
const DRONE_MATERIAL_KEY = 'tripo_material_abc4b498-0870-4cc4-87fa-155237fcc087'

type GLTFResult = GLTF & {
  nodes: Record<string, Mesh>
  materials: Record<string, MeshStandardMaterial>
}

type ModelProps = ThreeElements['group']

export function Model(props: ModelProps) {
  const groupRef = useRef<Group>(null)
  const { nodes, materials } = useGLTF('/drone3d.glb') as unknown as GLTFResult
  const node = nodes[DRONE_NODE_KEY]
  const material = materials[DRONE_MATERIAL_KEY]

  const brighterMaterial = useMemo(() => {
    if (!material) {
      return null
    }

    const nextMaterial = material.clone()
    nextMaterial.color = material.color.clone().multiplyScalar(1.6)
    nextMaterial.emissive = material.emissive.clone()
    nextMaterial.emissiveIntensity = Math.max(material.emissiveIntensity, 0.55)
    nextMaterial.roughness = Math.min(material.roughness, 0.45)

    return nextMaterial
  }, [material])

  useEffect(() => {
    return () => {
      brighterMaterial?.dispose()
    }
  }, [brighterMaterial])

  useFrame((_, delta) => {
    if (!groupRef.current) {
      return
    }

    groupRef.current.rotation.y += delta * 0.7
  })

  if (!node || !brighterMaterial) {
    return null
  }

  return (
    <group ref={groupRef} {...props}>
      <mesh castShadow receiveShadow geometry={node.geometry} material={brighterMaterial} />
    </group>
  )
}

useGLTF.preload('/drone3d.glb')
