// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config as loadEnv } from "dotenv";
import { defineConfig } from "prisma/config";
import { buildDatabaseUrl } from "./src/config/database-url";

const nodeEnv = process.env["NODE_ENV"] ?? "development";
const envFilePaths = [`.env.${nodeEnv}`, ".env"];

for (const envFilePath of envFilePaths) {
  loadEnv({ path: envFilePath, override: false });
}

const datasourceUrl = buildDatabaseUrl({
  databaseUrl: process.env["DATABASE_URL"],
  host: process.env["DATABASE_HOST"],
  port: process.env["DATABASE_PORT"],
  username: process.env["DATABASE_USERNAME"],
  password: process.env["DATABASE_PASSWORD"],
  name: process.env["DATABASE_NAME"],
});

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: datasourceUrl,
  },
});
